services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend_vue:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0